Description:
    The initial test set uses binary data. The data set is for Supervised Learning, the machine should tune itself to find a specific pattern.
    The input values are supposed to represent the values zero and one, although a machine can be trained better with fuzzy values which are not a One or a zero.

    Values which are close to "0" reprent a zero
    Values which are close to "1" represent a one.

The data file format:
    "input_1   input_2   input_3   output_1"



training_data:
    training_data_file_name: "example_1.data.train.cvs"
    number_of_input_neurons:    3
    number_of_hidden_neurons:   4
    number_of_hidden_layers:    1   
    number_of_outputs_neurons:  1
    number_of_training_iterations: 10000
    

machine_dump_file_name: "example_1.trained.machine.bin"
    
validation_data: "example_2.data.validate.cvs"