Description:
    The model was trained with the dataset "training_data_embedded"


general:
    verbose_logging: 0 

# a dropout of 20 percent may be used as starting point for pictures
# range [0 .. 100]
#dropout_percentage_range: [10, 20, 30, 40]
#dropout_percentage_range: [0]  # for this problem


# the default value for the L1L2 regulator is 0.01
#mkernel_regularizer_l2_range: [0.1, 0.01, 0.001, 0.0001]
#mkernel_regularizer_l2_range: [0.01]  # for this problem

early_stopping:
    monitor: 'val_loss'
    patience: 80000
    verbose: 0
    min_delta: 1e-8

learning_rate_scheduler:
    change_every_epochs: 10000  # looking at priminilary data, change at 10000
    change_divide_by: 10

machine:
    verbose: 0
    machine_dump_file_name_base: "xor3_v2"
    
    validate_data_during_fitting: 1
    
    number_of_epochs_range: [100000]  #we can use 100 000 - since we do early termination of an epoch
    #number_of_epochs_range: [2]
    
    #https://keras.io/api/layers/initializers/
    bias_initializer: 'zeros'   # default is zeros
    #bias_initializer: 'RandomNormal'   # default is zeros


    # optimizer
    #optimizer: "adam"
    optimizer: "SGD"
    learning_rate_range: [0.01, 0.001, 0.0001] # default for Adams is 0.001
    batch_size_range:  [5, 32]  # 32 default

    
    # loss function definiton
   # loss_function: 'MeanSquaredError'
   # metrics: ['mean_squared_logarithmic_error']
   
    #loss_function: 'binary_crossentropy'
    #metrics: ['accuracy']
    loss_function: 'MeanSquaredError'
    metrics: ['mean_squared_logarithmic_error', 'AUC']
    
      
    ### compistion of the engine
    number_of_input_neurons:    3
    
    number_of_hidden_neurons_layers_1_range: [4]
    #number_of_hidden_neurons_layers_1_range: [2]
    
    number_of_hidden_neurons_layers_2_range:  [0]
    #number_of_hidden_neurons_layers_2_range:  [0]
    
    number_of_outputs_neurons:  1
 
 
training_data:
    #training_data_file_name: "logical_xor3_v2.data.train.cvs"
    train_with_embedded : "training_data_embedded"
    training_data_embedded: [
        [0, 0, 0, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 1],
        [1, 0, 0, 1],
        [1, 1, 1, 0]
    ]
    

    


#validation_data_file_name: "logical_xor3.data.validate.cvs"   
validation_data_embedded: [
        [0.04, 0.06, 0.03, 0.0],
        
        [0.04, 0.05, 0.96, 1.0],
        [0.02, 0.93, 0.06, 1.0],
        [0.04, 0.94, 0.96, 1.0],
        [0.96, 0.07, 0.06, 1.0],
        [0.91, 0.08, 0.98, 1.0],
        [0.94, 0.95, 0.01, 1.0],
        
        [0.95, 0.99, 0.96, 0.0],
        
        [0.14, 0.06, 0.13, 0.0],
        
        [0.14, 0.15, 0.93, 1.0],
        [0.12, 0.91, 0.16, 1.0],
        [0.14, 0.90, 0.89, 1.0],
        [0.90, 0.17, 0.06, 1.0],
        [0.91, 0.05, 0.93, 1.0],
        [0.91, 0.93, 0.11, 1.0],
        
        [0.85, 0.89, 0.86, 0.0]
    ]








